#############################################################################
# Makefile for building: libdeepracin.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.8.6) on: Do. Mär 30 15:20:30 2017
# Project:  deepRACIN.pro
# Template: lib
# Command: /usr/share/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile deepRACIN.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_RELEASE
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I. -I/usr/lib/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -Iinclude -I../../Libs/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -shared -Wl,-soname,libdeepracin.so.1
LIBS          = $(SUBLIBS)   -lglib-2.0 -lOpenCL 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/share/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/deepRACIN.c \
		src/dR_clwrap.c \
		src/dR_core.c \
		src/dR_parser.c \
		src/dR_nodes_conv2d.c \
		src/dR_nodes_pooling.c \
		src/dR_nodes_fc.c \
		src/dR_nodes_misc.c \
		src/dR_nodes_math.c \
		src/dR_nodes_transform.c \
		src/dR_nodes_filter.c \
		src/dR_nodes_bn.c 
OBJECTS       = deepRACIN.o \
		dR_clwrap.o \
		dR_core.o \
		dR_parser.o \
		dR_nodes_conv2d.o \
		dR_nodes_pooling.o \
		dR_nodes_fc.o \
		dR_nodes_misc.o \
		dR_nodes_math.o \
		dR_nodes_transform.o \
		dR_nodes_filter.o \
		dR_nodes_bn.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/dll.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		deepRACIN.pro
QMAKE_TARGET  = deepracin
DESTDIR       = ../
TARGET        = libdeepracin.so.1.0.0
TARGETA       = ../libdeepracin.a
TARGETD       = libdeepracin.so.1.0.0
TARGET0       = libdeepracin.so
TARGET1       = libdeepracin.so.1
TARGET2       = libdeepracin.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  ../$(TARGET)

../$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) ../ || $(MKDIR) ../ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) ../$(TARGET)
	-$(DEL_FILE) ../$(TARGET0)
	-$(DEL_FILE) ../$(TARGET1)
	-$(DEL_FILE) ../$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) ../



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: deepRACIN.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/dll.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile deepRACIN.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/dll.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile deepRACIN.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/deepracin1.0.0 || $(MKDIR) .tmp/deepracin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/deepracin1.0.0/ && (cd `dirname .tmp/deepracin1.0.0` && $(TAR) deepracin1.0.0.tar deepracin1.0.0 && $(COMPRESS) deepracin1.0.0.tar) && $(MOVE) `dirname .tmp/deepracin1.0.0`/deepracin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/deepracin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) ../$(TARGET) 
	-$(DEL_FILE) ../$(TARGET0) ../$(TARGET1) ../$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

deepRACIN.o: src/deepRACIN.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o deepRACIN.o src/deepRACIN.c

dR_clwrap.o: src/dR_clwrap.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_clwrap.o src/dR_clwrap.c

dR_core.o: src/dR_core.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_core.o src/dR_core.c

dR_parser.o: src/dR_parser.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_parser.o src/dR_parser.c

dR_nodes_conv2d.o: src/dR_nodes_conv2d.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_conv2d.o src/dR_nodes_conv2d.c

dR_nodes_pooling.o: src/dR_nodes_pooling.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_pooling.o src/dR_nodes_pooling.c

dR_nodes_fc.o: src/dR_nodes_fc.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_fc.o src/dR_nodes_fc.c

dR_nodes_misc.o: src/dR_nodes_misc.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_misc.o src/dR_nodes_misc.c

dR_nodes_math.o: src/dR_nodes_math.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_math.o src/dR_nodes_math.c

dR_nodes_transform.o: src/dR_nodes_transform.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_transform.o src/dR_nodes_transform.c

dR_nodes_filter.o: src/dR_nodes_filter.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_filter.o src/dR_nodes_filter.c

dR_nodes_bn.o: src/dR_nodes_bn.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o dR_nodes_bn.o src/dR_nodes_bn.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

